[cvnmount-tui] Use select to let the user choose a mount point to mount
This should present the gathered user-mountable mount points
to the user as a (possibly) multi-column list with numbers by them.
The user will just need to enter the associated number to select
a mount point for mounting. Entering 0 exits, and pressing ^D (EOT)
appears to exit non-zero.

diff --git a/cvnmount-tui b/cvnmount-tui
--- a/cvnmount-tui
+++ b/cvnmount-tui
@@ -20,4 +20,12 @@ do
 	USER_DSTS=("${USER_DSTS[@]}" "$DST")
 done </etc/fstab
 
-echo "User-mountable mount points: ${USER_DSTS[*]}"
+echo "Select a user-mountable mount point to mount:"
+
+select DST in "${USER_DSTS[@]}"
+do
+	[ -n "$DST" ] || { echo "Exit."; break; }
+
+	echo "Mounting $DST ..."
+	mount "$DST" || warn "Error: mount failed"
+done
