[cvnmount-tui] Include mount point in error message
The mount point was output before, but it would have been missing
from only looking at stderr.

diff --git a/cvnmount-tui b/cvnmount-tui
--- a/cvnmount-tui
+++ b/cvnmount-tui
@@ -27,5 +27,5 @@ do
 	[ -n "$DST" ] || { echo "Exit."; break; }
 
 	echo "Mounting $DST ..."
-	mount "$DST" || warn "Error: mount failed"
+	mount "$DST" || warn "Error: Mounting $DST failed"
 done
